# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H8fHB4nz86ATyVJnx4txywDHSTiG0qj1
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 4.0 * np.pi, 129)
y = np.sin(x)
plt.plot(x, y)
plt.plot(x, np.cos(x))
plt.plot(x, np.tan(x))

plt.show

np.linspace(0, 4.0 * np.pi, 5)

"""The linespace gives x points of values between ValueMin and ValueMax"""

np.linspace(0, 4.0 * np.pi, 5)

"""To generate number between 0-100 with 10 space"""

np.linspace(0, 100, 11)

"""is seen seen that when i"""

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 4.0 * np.pi, 129)
y = np.sin(x)
plt.plot(x, y)
plt.plot(x, np.cos(x), "r")

plt.show

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 4.0 * np.pi, 129)
plt.plot(x, np.cos(x), "g*-.")

plt.show

"""#### *for marker points*"""

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 4.0 * np.pi, 129)
plt.plot(x, np.cos(x), marker="o")

plt.show

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 4.0 * np.pi, 129)
plt.plot(x, np.cos(x), "o")
plt.show

"""The Both method works the *same*....."""

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 4.0 * np.pi, 129)
plt.figure(1)
plt.plot(x, np.cos(x), marker="o")
plt.figure(2)
plt.plot(x, np.sin(x), "r")

plt.show

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-10.0, 10.0, 200)
ysin = np.sin(x)

# Create cos array
ycos = np.cos(x)

np.linspace(-10, 10, 200) == np.linspace(-10.0, 10.0, 200)
